//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleChecklist.Core {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleChecklist.Core.AppTexts", typeof(AppTexts).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © Mateusz Ucher 2017.
        /// </summary>
        public static string AboutPageText {
            get {
                return ResourceManager.GetString("AboutPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mateusz Ucher - English, Polish.
        /// </summary>
        public static string AboutPageTranslatorsListText {
            get {
                return ResourceManager.GetString("AboutPageTranslatorsListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations:.
        /// </summary>
        public static string AboutPageTranslatorsText {
            get {
                return ResourceManager.GetString("AboutPageTranslatorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string AboutPageVersionText {
            get {
                return ResourceManager.GetString("AboutPageVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddTaskButtonText {
            get {
                return ResourceManager.GetString("AddTaskButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid backup data format..
        /// </summary>
        public static string BackupLoadError {
            get {
                return ResourceManager.GetString("BackupLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create backup file....
        /// </summary>
        public static string CreateBackupButtonText {
            get {
                return ResourceManager.GetString("CreateBackupButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DonePageTitle {
            get {
                return ResourceManager.GetString("DonePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the name &apos;{0}&apos; already exists. Do you want to overwrite this file?.
        /// </summary>
        public static string FileAlreadyExist {
            get {
                return ResourceManager.GetString("FileAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load backup from file....
        /// </summary>
        public static string LoadBackupButtonText {
            get {
                return ResourceManager.GetString("LoadBackupButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to replace current data using backup?.
        /// </summary>
        public static string LoadBackupConfirmationText {
            get {
                return ResourceManager.GetString("LoadBackupConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during loading data. If you continue to run application you may lose your data.
        ///
        ///Do you want to stop initialization?.
        /// </summary>
        public static string LoadErrorConfirmationText {
            get {
                return ResourceManager.GetString("LoadErrorConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tasks from text file....
        /// </summary>
        public static string LoadTasksFromTextFileButtonText {
            get {
                return ResourceManager.GetString("LoadTasksFromTextFileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to add tasks from text file?.
        /// </summary>
        public static string LoadTasksFromTextFileConfirmationText {
            get {
                return ResourceManager.GetString("LoadTasksFromTextFileConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove selected task?.
        /// </summary>
        public static string RemoveTaskConfirmationText {
            get {
                return ResourceManager.GetString("RemoveTaskConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string TaskListPageTitle {
            get {
                return ResourceManager.GetString("TaskListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid text file format.
        ///Please use UTF-8 encoding and write each task in separate line..
        /// </summary>
        public static string TextFileLoadError {
            get {
                return ResourceManager.GetString("TextFileLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to move back selected task to undone tasks list?.
        /// </summary>
        public static string UndoneTaskConfirmationText {
            get {
                return ResourceManager.GetString("UndoneTaskConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
